plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.10'
    id 'io.quarkus' version '3.31.2'
    id 'com.google.protobuf' version '0.9.4'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'io.quarkus:quarkus-websockets'
    implementation 'io.quarkus:quarkus-redis-client'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'com.google.protobuf:protobuf-java:3.25.8'
    
    testImplementation 'io.quarkus:quarkus-junit5'
}

group 'com.edgecell'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

compileKotlin {
    kotlinOptions.jvmTarget = "25"
    kotlinOptions.javaParameters = true
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "25"
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.8'
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {}
            }
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir 'src/main/proto'
        }
    }
}
